Repository utra-robosoccer/soccer-embedded, pull requests merged in 2018-09, with the labels that each got.

#70 RobotTest: Add PcInterface class, with tests and mocks
  RobotTest/inc/LwipUdpInterface.h
  RobotTest/inc/PcInterface.h
  RobotTest/inc/UdpInterface.h
  RobotTest/src/LwipUdpInterface.cpp
  RobotTest/src/PcInterface.cpp
  RobotTest/src/PcInterface_test.cpp
Labels: Module: PC Comm

#73 Diagrams: add updated robot development path
  Diagrams/robot_dev_path.png
  Diagrams/robot_dev_path.xml
Labels: Type: Documentation

#74 Update design files and images
  Robot/Doc/Media/Design_Future_2018/August-6-2018-Design.pptx
  Robot/Doc/Media/Design_Future_2018/August-6-2018-Design_Full.png
  Robot/Doc/Media/Design_Future_2018/August-6-2018-Design_Full.pptx
  Robot/Doc/Media/Design_Future_2018/August-6-2018-Equipment_Command_Cache.png
Labels: Type: Documentation

#82 Motor imitation program updates
  Development/F7_Validation/L432_Helper/Inc/helpers.h
  Development/F7_Validation/L432_Helper/Inc/lfsr.h
  Development/F7_Validation/L432_Helper/Inc/rx_helpers.h
  Development/F7_Validation/L432_Helper/Inc/tx_helpers.h
  Development/F7_Validation/L432_Helper/Inc/types.h
  Development/F7_Validation/L432_Helper/Src/freertos.c
  Development/F7_Validation/L432_Helper/Src/helpers.c
  Development/F7_Validation/L432_Helper/Src/rx_helpers.c
  Development/F7_Validation/L432_Helper/Src/tx_helpers.c
Labels: Type: Infrastructure

#85 Freertos testing
  .gitignore
  Robot/.settings/language.settings.xml
  RobotTest/.cproject
  RobotTest/inc/FreeRTOSInterface.h
  RobotTest/inc/FunctionalFreeRTOSInterface.h
  RobotTest/inc/UdpInterface.h
  RobotTest/src/FreeRTOSInterface_test.cpp
  RobotTest/src/FunctionalFreeRTOSInterface.cpp
Labels: Type: Testing

#91 UART mocking
  RobotTest/.cproject
  RobotTest/inc/FreeRTOSInterface.h
  RobotTest/inc/FunctionalFreeRTOSInterface.h
  RobotTest/inc/HalUartInterface.h
  RobotTest/inc/MockFreeRTOSInterface.h
  RobotTest/inc/MockUartInterface.h
  RobotTest/inc/UartDriver.h
  RobotTest/inc/UartInterface.h
  RobotTest/src/FreeRTOSInterface_test.cpp
  RobotTest/src/FunctionalFreeRTOSInterface.cpp
  RobotTest/src/HalUartInterface.cpp
  RobotTest/src/UartDriver.cpp
  RobotTest/src/UartDriver_test.cpp
Labels: Type: Testing

#86 Implement cpp functionality for the MPU6050
  Robot/Doc/Doxyfile
  Robot/Drivers/MPU6050/MPU6050.c
  Robot/Drivers/MPU6050/MPU6050.cpp
  Robot/Drivers/MPU6050/MPU6050.h
  Robot/Drivers/MPU6050/MPUFilter.cpp
  Robot/Drivers/MPU6050/MPUFilter.h
  Robot/F4.cfg
  Robot/Inc/UART_Handler.h
  Robot/Src/freertos.cpp
Labels: Module: IMU

#83 Refactoring StartRXTask(), StartTXTask()
  Development/Foot_Pressure_Sensor_Standalone/MCU-Side/Foot_Pressure_Sensor_v1/.settings/language.settings.xml
  Robot/.settings/language.settings.xml
  Robot/Inc/rx_helper.h
  Robot/Inc/tx_helper.h
  Robot/Src/freertos.cpp
  Robot/Src/rx_helper.cpp
  Robot/Src/tx_helper.cpp
  RobotTest/.settings/language.settings.xml
Labels: Type: Enhancement
