Repository utra-robosoccer/soccer-embedded, pull requests merged in 2018-07, with the labels that each got.

#11 Remove absolute path for input
  Robot/.settings/language.settings.xml
  Robot/Doc/Doxyfile
  Robot/Doc/html/main_8h.html
Labels: Priority: Medium, Type: Maintenance

#13 Fix some Dynamixel documentation that was generating warnings
  Robot/Doc/html/_dynamixel_protocol_v1_8c.html
  Robot/Doc/html/_dynamixel_protocol_v1_8c.js
  Robot/Doc/html/_dynamixel_protocol_v1_8h_source.html
  Robot/Doc/html/globals_a.html
  Robot/Doc/html/globals_vars.html
  Robot/Doc/html/group___a_x12_a___interfaces.html
  Robot/Doc/html/group___a_x12_a_header.html
  Robot/Doc/html/group___dynamixel_protocol_v1___public___functions___l_l___t_x___r_x.html
  Robot/Doc/html/group___dynamixel_protocol_v1___public___functions___library___configuration.html
  Robot/Doc/html/group___dynamixel_protocol_v1___public___functions___other.html
  Robot/Doc/html/group___dynamixel_protocol_v1___public___functions___setters.html
  Robot/Doc/html/group___dynamixel_protocol_v1_header.html
  Robot/Doc/html/navtreedata.js
  Robot/Doc/html/navtreeindex0.js
  Robot/Doc/html/navtreeindex1.js
  Robot/Doc/html/navtreeindex2.js
  Robot/Doc/html/search/all_1.js
  Robot/Doc/html/search/variables_1.js
  Robot/Drivers/Dynamixel/AX12A/AX12A.c
  Robot/Drivers/Dynamixel/DynamixelProtocolV1.c
  Robot/Drivers/Dynamixel/DynamixelProtocolV1.h
Labels: Priority: Medium, Type: Maintenance

#15 added new MPU6050 module for doxygen
  Robot/Drivers/MPU6050/MPU6050.c
Labels: Priority: Medium, Type: Documentation

#19 Doxygen integration for MPU6050
  .gitignore
  Robot/Drivers/MPU6050/MPU6050.c
  Robot/Drivers/MPU6050/MPU6050.h
Labels: Priority: Medium, Type: Documentation

#29 Code style: Replace tabs with spaces
  Robot/Drivers/Dynamixel/AX12A/AX12A.c
  Robot/Drivers/Dynamixel/DynamixelProtocolV1.c
  Robot/Drivers/Dynamixel/MX28/MX28.c
  Robot/Src/UART_Handler.c
  Robot/Src/freertos.c
Labels: Priority: Low, Type: Maintenance

#42 Cpp build
  Templates/example_cpp.cpp
  Templates/example_cpp.h
Labels: Priority: Low, Type: Documentation

#44 Urgent issue with master: wrong task notified after refactor
  Development/Comm-PC/comm.py
  Robot/Src/freertos.c
Labels: Module: FreeRTOS, Priority: Critical, Type: Bug
