Repository utra-robosoccer/soccer-embedded, pull requests merged in 2018-11, with the labels that each got.

#108 Convert Dynamixel libraries to C++
  Common/app/PeripheralInstances.cpp
  Common/app/freertos.cpp
  Common/app/tx_helper.cpp
  Common/app/uart_handler.cpp
  Common/component/DaisyChain/DaisyChain.cpp
  Common/component/Dynamixel/AX12A.cpp
  Common/component/Dynamixel/AX12A/AX12A.c
  Common/component/Dynamixel/Dynamixel.cpp
  Common/component/Dynamixel/MX28.cpp
  Common/component/Dynamixel/MX28/MX28.c
  Common/component/Dynamixel/ProtocolV1/DynamixelProtocolV1.c
  Common/component/Dynamixel/ProtocolV1/IO/DynamixelProtocolV1_IO.c
  Common/component/Dynamixel/h/AX12A.h
  Common/component/Dynamixel/h/DynamixelProtocolV1_IO.h
  Common/component/Dynamixel/h/Dynamixel_Data.h
  Common/component/Dynamixel/h/Dynamixel_Types.h
  Common/component/Dynamixel/h/MX28.h
  Common/component/UartDriver/UartDriver.cpp
  Common/hardware/GpioInterfaceImpl.cpp
  Common/hardware/HalUartInterface.cpp
  Common/hardware/OsInterfaceImpl.cpp
  Common/include/AX12A.h
  Common/include/DaisyChain.h
  Common/include/Dynamixel.h
  Common/include/DynamixelProtocolV1.h
  Common/include/GpioInterface.h
  Common/include/GpioInterfaceImpl.h
  Common/include/HalUartInterface.h
  Common/include/LwipUdpInterface.h
  Common/include/MPU6050.h
  Common/include/MX28.h
  Common/include/MockGpioInterface.h
  Common/include/MockMotor.h
  Common/include/MockOsInterface.h
  Common/include/MockUartInterface.h
  Common/include/OsInterface.h
  Common/include/PcInterface.h
  Common/include/PeripheralInstances.h
  Common/include/UartDriver.h
  Common/include/UartInterface.h
  Common/include/UdpInterface.h
  Common/include/uart_handler.h
  Common/test/AX12A_test.cpp
  Common/test/DaisyChain_test.cpp
  Common/test/MX28_test.cpp
  Common/test/Motor_test.cpp
  Common/test/UartDriver_test.cpp
  RobotTest/.cproject
  RobotTest/.settings/language.settings.xml
  Robot_F4/.settings/language.settings.xml
  Robot_F7/.settings/language.settings.xml
Labels: Module: Dynamixel, Type: Enhancement

#111 Gdharan data cache
  .gitignore
  Common/app/freertos.cpp
  Common/include/BufferBase.h
  Common/include/uart_handler.h
  Common/test/Buffer_test.cpp
  RobotTest/.settings/language.settings.xml
  Robot_F4/.cproject
  Robot_F4/.mxproject
  Robot_F4/.project
  Robot_F4/.settings/language.settings.xml
  Robot_F4/Robot_F4.ioc
  Robot_F4/Robot_F4.xml
  Robot_F7/.cproject
  Robot_F7/.settings/language.settings.xml
  Robot_F7/NUCLEO-F767ZI.xml
  Robot_F7/Robot_F7.ioc
Labels: Type: Feature

#118 Add pics for stm32 getting started tutorial
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/1-Board-Select.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/10-GPIO-APIs.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/11-GPIO-decl-in-main.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/12-Compiling.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/13-Running.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/14-Debugging.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/2-Blank-Project.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/3-Project-Settings-Location.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/4-Project-Settings-1.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/5-Project-Settings-2.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/6-LED-Pin.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/7-GPIO-Config.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/8-Generate-Code.jpg
  Diagrams/wiki/stm32/Getting-Started-with-Cube-and-System-Workbench/9-System-Workbench-Project-Explorer.jpg
Labels: Type: Documentation

#116 Gdharan buffer writer
  Common/app/freertos.cpp
  Common/app/tx_helper.cpp
  Common/app/uart_handler.cpp
  Common/include/BufferBase.h
  Common/include/tx_helper.h
  Common/include/uart_handler.h
Labels: Type: Feature

#119 Add pics for STM32 serial communication tutorial
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/1-USART2-Pins.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/2-USART-Params.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/3-USART-NVIC.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/4-USART-DMA.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/5-Clock-Config.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/6-Callbacks.jpg
  Diagrams/wiki/stm32/Communication-Between-MCU-and-PC/7-DMA-Circular-Receive.jpg
Labels: Type: Documentation

#120 OS Interface + Static Buffer Allocation
  Common/app/freertos.cpp
  Common/include/BufferBase.h
  Common/test/Buffer_test.cpp
Labels: Type: Maintenance

#125 Wait for motors to turn on before sending init commands
  Common/app/freertos.cpp
Labels: Type: Bug

#132 Minor changes to mainpage + FreeRTOS wiki images
  Diagrams/wiki/stm32/Getting-Started-with-FreeRTOS/2-FreeRTOS-config.jpg
  Diagrams/wiki/stm32/Getting-Started-with-FreeRTOS/3-FreeRTOS-includes.jpg
  Diagrams/wiki/stm32/Getting-Started-with-FreeRTOS/3-FreeRTOS-includes1.jpg
  docs/mainpage.md
Labels: Type: Documentation

#109 smoketest: Communication using UartDriver and CircularDmaBuffer + Sync up other bits
  Common/app/freertos.cpp
  Common/app/rx_helper.cpp
  Common/app/tx_helper.cpp
  Common/component/CircularDmaBuffer/CircularDmaBuffer.cpp
  Common/component/PcInterface/PcInterface.cpp
  Common/component/UartDriver/UartDriver.cpp
  Common/component/UdpDriver/UdpDriver.cpp
  Common/hardware/HalUartInterface.cpp
  Common/hardware/LwipUdpInterface.cpp
  Common/hardware/OsInterfaceImpl.cpp
  Common/include/CircularDmaBuffer.h
  Common/include/HalUartInterface.h
  Common/include/LwipUdpInterface.h
  Common/include/MockOsInterface.h
  Common/include/MockUartInterface.h
  Common/include/MockUdpInterface.h
  Common/include/OsInterface.h
  Common/include/OsInterfaceImpl.h
  Common/include/PcInterface.h
  Common/include/UartDriver.h
  Common/include/UartInterface.h
  Common/include/UdpDriver.h
  Common/include/UdpInterface.h
  Common/include/rx_helper.h
  Common/include/tx_helper.h
  Common/test/CircularDmaBuffer_test.cpp
  Common/test/PcInterface_test.cpp
  Common/test/UdpDriver_test.cpp
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/Inc/lwipopts.h
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/NUCLEO-F767ZI.xml
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/Src/freertos.c
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/Src/lwip.c
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/lwip-rtos-config Run.cfg
  Development/Ethernet/lwip-rtos-config/lwip-rtos-config/lwip-rtos-config.ioc
  RobotTest/.cproject
  RobotTest/.settings/language.settings.xml
  Robot_F4/.cproject
  Robot_F4/Src/usart.c
  Robot_F7/.settings/language.settings.xml
  Robot_F7/.settings/org.eclipse.cdt.codan.core.prefs
  Robot_F7/Inc/stm32f7xx_it.h
  Robot_F7/Robot_F7.ioc
  Robot_F7/Src/main.cpp
  Robot_F7/Src/stm32f7xx_it.c
  Templates/template_cpp.cpp
Labels: Module: PC Comm, Type: Feature

#131 Check whether motors were read from successfully before buffering data
  Common/app/freertos.cpp
  Common/app/uart_handler.cpp
  Common/include/uart_handler.h
Labels: Module: FreeRTOS, Priority: Medium, Type: Bug
