Repository utra-robosoccer/soccer-embedded, pull requests merged in 2019-02, with the labels that each got.

#181 Gdharan add travis
  .travis.yml
Labels: Type: Infrastructure

#173 SystemConf.h: make UART handle declarations macros / fix unit tests
  Common/include/SystemConf.h
  RobotTest/.cproject
  RobotTest/.settings/language.settings.xml
Labels: Type: Bug

#175 tidy ups to SystemConf
  Common/component/MPU6050/MPU6050.cpp
  Common/include/GpioInterface.h
  Common/include/I2CInterface.h
  Common/include/MPU6050.h
  Common/include/OsInterface.h
Labels: Type: Maintenance

#169 Add CONTRIBUTING.md with style guide
  CONTRIBUTING.md
  Templates/c/example.c
  Templates/cpp/servo_ex_cpp.cpp
Labels: Type: Documentation

#176 Declare new mock objects per unit test (through fixture or a new declaration in each test)
  Common/test/AX12A_test.cpp
  Common/test/Buffer_test.cpp
  Common/test/CircularDmaBuffer_test.cpp
  Common/test/DaisyChain_test.cpp
  Common/test/MX28_test.cpp
  Common/test/Motor_test.cpp
  Common/test/UdpDriver_test.cpp
Labels: Type: Maintenance
