Repository utra-robosoccer/soccer-embedded, pull requests merged in 2019-03, with the labels that each got.

#185 Move includes to same folder as source files
  Common/app/Communication.c
  Common/app/Communication.h
  Common/app/freertos.cpp
  Common/app/imu_helper.cpp
  Common/app/imu_helper.h
  Common/app/robotGoal.h
  Common/app/robotState.h
  Common/app/rx_helper.h
  Common/app/tx_helper.cpp
  Common/app/tx_helper.h
  Common/component/CircularDmaBuffer/CircularDmaBuffer.h
  Common/component/DSP/dsp.h
  Common/component/DaisyChain/DaisyChain.h
  Common/component/Dynamixel/AX12A.h
  Common/component/Dynamixel/Dynamixel.h
  Common/component/Dynamixel/MX28.h
  Common/component/MPU6050/MPU6050.h
  Common/component/UartDriver/UartDriver.h
  Common/component/UdpDriver/UdpDriver.h
  Common/hardware/GpioInterfaceImpl.h
  Common/hardware/HalI2CInterface.h
  Common/hardware/HalUartInterface.h
  Common/hardware/LwipUdpInterface.h
  Common/hardware/OsInterfaceImpl.h
  Common/include/Mocks.h
  Common/include/PeripheralInstances.h
  Common/include/uart_handler.h
  Common/interface/GpioInterface.h
  Common/interface/I2CInterface.h
  Common/interface/OsInterface.h
  Common/interface/UartInterface.h
  Common/interface/UdpInterface.h
  Common/mock/MockGpioInterface.h
  Common/mock/MockI2CInterface.h
  Common/mock/MockMotor.h
  Common/mock/MockOsInterface.h
  Common/mock/MockUartInterface.h
  Common/mock/MockUdpInterface.h
  Common/test/AX12A_test.cpp
  Common/test/Buffer_test.cpp
  Common/test/CircularDmaBuffer_test.cpp
  Common/test/DaisyChain_test.cpp
  Common/test/MX28_test.cpp
  Common/test/UartDriver_test.cpp
  Common/test/UdpDriver_test.cpp
  Robot/.cproject
  Robot/.project
  Robot/makefile
  RobotTest/.cproject
Labels: Type: Maintenance

#189 Rename hardware, interface, mock, and Udp namespaces
  Common/app/PeripheralInstances.cpp
  Common/app/freertos.cpp
  Common/component/CircularDmaBuffer/CircularDmaBuffer.h
  Common/component/DaisyChain/DaisyChain.h
  Common/component/UartDriver/UartDriver.h
  Common/component/UdpDriver/UdpDriver.cpp
  Common/component/UdpDriver/UdpDriver.h
  Common/hardware/GpioInterfaceImpl.cpp
  Common/hardware/GpioInterfaceImpl.h
  Common/hardware/HalI2CInterface.h
  Common/hardware/HalI2cInterface.cpp
  Common/hardware/HalUartInterface.cpp
  Common/hardware/HalUartInterface.h
  Common/hardware/LwipUdpInterface.cpp
  Common/hardware/OsInterfaceImpl.cpp
  Common/hardware/OsInterfaceImpl.h
  Common/hardware/UdpRawInterfaceImpl.cpp
  Common/hardware/UdpRawInterfaceImpl.h
  Common/include/BufferBase.h
  Common/interface/GpioInterface.h
  Common/interface/I2CInterface.h
  Common/interface/OsInterface.h
  Common/interface/UartInterface.h
  Common/interface/UdpRawInterface.h
  Common/mock/MockGpioInterface.h
  Common/mock/MockI2CInterface.h
  Common/mock/MockMotor.h
  Common/mock/MockOsInterface.h
  Common/mock/MockUartInterface.h
  Common/mock/UdpRawInterfaceMock.h
  Common/test/AX12A_test.cpp
  Common/test/Buffer_test.cpp
  Common/test/CircularDmaBuffer_test.cpp
  Common/test/DaisyChain_test.cpp
  Common/test/MX28_test.cpp
  Common/test/Motor_test.cpp
  Common/test/UartDriver_test.cpp
  Common/test/UdpDriver_test.cpp
  Robot/.cproject
  Robot/.project
  Robot/.settings/language.settings.xml
  Robot/makefile
Labels: Priority: Medium, Type: Maintenance

#182 Motor IDing Tool
  Development/Motor_ID/.cproject
  Development/Motor_ID/.settings/org.eclipse.cdt.codan.core.prefs
  Development/Motor_ID/Motor_Test_1 Debug.cfg
  Development/Motor_ID/iding_cmd.py
Labels: Priority: Low, Type: Enhancement

#190 Enable parallel compilation (~5x compile time speedup)
  .travis.yml
  Robot/.cproject
Labels: Type: Infrastructure

#193 Rename identifiers
  Common/app/Communication.cpp
  Common/app/Communication.h
  Common/app/PeripheralInstances.cpp
  Common/app/freertos.cpp
  Common/app/imu_helper.cpp
  Common/app/imu_helper.h
  Common/app/robotGoal.h
  Common/app/robotState.h
  Common/app/rx_helper.cpp
  Common/app/tx_helper.cpp
  Common/app/tx_helper.h
  Common/app/uart_handler.cpp
  Common/component/CircularDmaBuffer/CircularDmaBuffer.cpp
  Common/component/CircularDmaBuffer/CircularDmaBuffer.h
  Common/component/DSP/dsp.cpp
  Common/component/DSP/dsp.h
  Common/component/DaisyChain/DaisyChain.cpp
  Common/component/DaisyChain/DaisyChain.h
  Common/component/Dynamixel/AX12A.cpp
  Common/component/Dynamixel/AX12A.h
  Common/component/Dynamixel/Dynamixel.cpp
  Common/component/Dynamixel/Dynamixel.h
  Common/component/Dynamixel/MX28.cpp
  Common/component/Dynamixel/MX28.h
  Common/component/MPU6050/MPU6050.cpp
  Common/component/MPU6050/MPU6050.h
  Common/component/UartDriver/UartDriver.cpp
  Common/component/UartDriver/UartDriver.h
  Common/include/BufferBase.h
  Common/include/Notification.h
  Common/include/PeripheralInstances.h
  Common/include/SystemConf.h
  Common/include/uart_handler.h
  Common/test/Buffer_test.cpp
  CubeMX/F4/Robot_F4.ioc
  CubeMX/F7/Robot_F7.ioc
Labels: Priority: Medium, Type: Maintenance

#194 Update Udp identifiers, rename hardware and mock filenames/classes, remove filename from @file and add script for it
  CONTRIBUTING.md
  Common/app/PeripheralInstances.cpp
  Common/app/freertos.cpp
  Common/app/imu_helper.cpp
  Common/app/imu_helper.h
  Common/app/rx_helper.h
  Common/app/tx_helper.cpp
  Common/app/tx_helper.h
  Common/component/UartDriver/UartDriver.cpp
  Common/component/UartDriver/UartDriver.h
  Common/component/UdpDriver/UdpDriver.cpp
  Common/component/UdpDriver/UdpDriver.h
  Common/hardware/GpioInterfaceImpl.cpp
  Common/hardware/GpioInterfaceImpl.h
  Common/hardware/I2CInterfaceImpl.cpp
  Common/hardware/I2CInterfaceImpl.h
  Common/hardware/OsInterfaceImpl.cpp
  Common/hardware/OsInterfaceImpl.h
  Common/hardware/UartInterfaceImpl.cpp
  Common/hardware/UartInterfaceImpl.h
  Common/hardware/UdpRawInterfaceImpl.cpp
  Common/interface/GpioInterface.h
  Common/interface/I2CInterface.h
  Common/interface/OsInterface.h
  Common/interface/UartInterface.h
  Common/interface/UdpRawInterface.h
  Common/mock/GpioInterfaceMock.h
  Common/mock/I2CInterfaceMock.h
  Common/mock/MotorMock.h
  Common/mock/OsInterfaceMock.h
  Common/mock/UartInterfaceMock.h
  Common/test/AX12ATest.cpp
  Common/test/BufferTest.cpp
  Common/test/CircularDmaBufferTest.cpp
  Common/test/DaisyChainTest.cpp
  Common/test/MX28Test.cpp
  Common/test/MotorTest.cpp
  Common/test/UartDriverTest.cpp
  Common/test/UdpDriverTest.cpp
  Robot/.cproject
  RobotTest/.cproject
  utils/clear_doxygen_file_tags.py
Labels: Priority: Medium, Type: Maintenance

#199 Fix IMU data offset in transmitted packet
  Common/app/tx_helper.cpp
Labels: Module: IMU, Priority: Critical, Type: Bug
