Repository utra-robosoccer/soccer-embedded, pull requests merged in 2019-01, with the labels that each got.

#164 Update development path
  Diagrams/robot_dev_path.png
  Diagrams/robot_dev_path.xml
Labels: Type: Documentation

#162 Update templates and example
  Templates/c/example.c
  Templates/c/example.h
  Templates/c/template_c.c
  Templates/c/template_c.h
  Templates/cpp/servo_ex_cpp.cpp
  Templates/cpp/servo_ex_cpp.h
  Templates/cpp/template_cpp.cpp
  Templates/cpp/template_cpp.h
  Templates/example_c.c
  Templates/example_c.h
  Templates/template_c.c
  Templates/template_c.h
Labels: Type: Maintenance

#165 Gdharan makefiles
  .gitignore
  Robot_F4/.cproject
  Robot_F4/Robot_F4 Debug.cfg
  Robot_F4/Robot_F4 Run.cfg
  Robot_F4/Robot_F4.cfg
  Robot_F4/Robot_F4.launch
  Robot_F4/makefile
  Robot_F7/.cproject
  Robot_F7/.settings/language.settings.xml
  Robot_F7/Robot_F7.cfg
  Robot_F7/Robot_F7.launch
  Robot_F7/makefile
Labels: Type: Infrastructure
